# Generated by Django 3.0.2 on 2020-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200116_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='categories',
            field=models.ManyToManyField(related_name='threads', to='dashboard.Category'),
        ),
    ]
